var files =
[
    [ "applyLUT.cpp", "apply_l_u_t_8cpp.html", null ],
    [ "applyLUT.h", "apply_l_u_t_8h.html", [
      [ "applyLUTException", "classpuntoexe_1_1imebra_1_1transforms_1_1apply_l_u_t_exception.html", null ]
    ] ],
    [ "baseObject.cpp", "base_object_8cpp.html", null ],
    [ "baseObject.h", "base_object_8h.html", null ],
    [ "baseStream.cpp", "base_stream_8cpp.html", null ],
    [ "baseStream.h", "base_stream_8h.html", null ],
    [ "buffer.cpp", "buffer_8cpp.html", null ],
    [ "buffer.h", "buffer_8h.html", null ],
    [ "charsetConversion.h", "charset_conversion_8h.html", null ],
    [ "charsetConversionIconv.cpp", "charset_conversion_iconv_8cpp.html", null ],
    [ "charsetConversionIconv.h", "charset_conversion_iconv_8h.html", null ],
    [ "charsetConversionICU.cpp", "charset_conversion_i_c_u_8cpp.html", null ],
    [ "charsetConversionICU.h", "charset_conversion_i_c_u_8h.html", null ],
    [ "charsetConversionWindows.cpp", "charset_conversion_windows_8cpp.html", null ],
    [ "charsetConversionWindows.h", "charset_conversion_windows_8h.html", null ],
    [ "charsetsList.cpp", "charsets_list_8cpp.html", null ],
    [ "charsetsList.h", "charsets_list_8h.html", "charsets_list_8h" ],
    [ "codec.cpp", "codec_8cpp.html", null ],
    [ "codec.h", "codec_8h.html", null ],
    [ "codecFactory.cpp", "codec_factory_8cpp.html", null ],
    [ "codecFactory.h", "codec_factory_8h.html", null ],
    [ "colorTransform.cpp", "color_transform_8cpp.html", null ],
    [ "colorTransform.h", "color_transform_8h.html", null ],
    [ "colorTransformsFactory.cpp", "color_transforms_factory_8cpp.html", null ],
    [ "colorTransformsFactory.h", "color_transforms_factory_8h.html", null ],
    [ "configuration.h", "configuration_8h.html", "configuration_8h" ],
    [ "criticalSection.cpp", "critical_section_8cpp.html", null ],
    [ "criticalSection.h", "critical_section_8h.html", null ],
    [ "data.cpp", "data_8cpp.html", null ],
    [ "data.h", "data_8h.html", null ],
    [ "dataCollection.h", "data_collection_8h.html", null ],
    [ "dataGroup.cpp", "data_group_8cpp.html", null ],
    [ "dataGroup.h", "data_group_8h.html", null ],
    [ "dataHandler.cpp", "data_handler_8cpp.html", null ],
    [ "dataHandler.h", "data_handler_8h.html", [
      [ "dataHandler", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler" ]
    ] ],
    [ "dataHandlerDate.cpp", "data_handler_date_8cpp.html", null ],
    [ "dataHandlerDate.h", "data_handler_date_8h.html", [
      [ "dataHandlerDate", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date" ]
    ] ],
    [ "dataHandlerDateTime.cpp", "data_handler_date_time_8cpp.html", null ],
    [ "dataHandlerDateTime.h", "data_handler_date_time_8h.html", null ],
    [ "dataHandlerDateTimeBase.cpp", "data_handler_date_time_base_8cpp.html", null ],
    [ "dataHandlerDateTimeBase.h", "data_handler_date_time_base_8h.html", [
      [ "dataHandlerDateTimeBase", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date_time_base.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date_time_base" ]
    ] ],
    [ "dataHandlerNumeric.h", "data_handler_numeric_8h.html", "data_handler_numeric_8h" ],
    [ "dataHandlerString.cpp", "data_handler_string_8cpp.html", null ],
    [ "dataHandlerString.h", "data_handler_string_8h.html", [
      [ "dataHandlerString", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string" ]
    ] ],
    [ "dataHandlerStringAE.cpp", "data_handler_string_a_e_8cpp.html", null ],
    [ "dataHandlerStringAE.h", "data_handler_string_a_e_8h.html", [
      [ "dataHandlerStringAE", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_e.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_e" ]
    ] ],
    [ "dataHandlerStringAS.cpp", "data_handler_string_a_s_8cpp.html", null ],
    [ "dataHandlerStringAS.h", "data_handler_string_a_s_8h.html", [
      [ "dataHandlerStringAS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_s" ]
    ] ],
    [ "dataHandlerStringCS.cpp", "data_handler_string_c_s_8cpp.html", null ],
    [ "dataHandlerStringCS.h", "data_handler_string_c_s_8h.html", [
      [ "dataHandlerStringCS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_c_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_c_s" ]
    ] ],
    [ "dataHandlerStringDS.cpp", "data_handler_string_d_s_8cpp.html", null ],
    [ "dataHandlerStringDS.h", "data_handler_string_d_s_8h.html", [
      [ "dataHandlerStringDS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_d_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_d_s" ]
    ] ],
    [ "dataHandlerStringIS.cpp", "data_handler_string_i_s_8cpp.html", null ],
    [ "dataHandlerStringIS.h", "data_handler_string_i_s_8h.html", [
      [ "dataHandlerStringIS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_i_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_i_s" ]
    ] ],
    [ "dataHandlerStringLO.cpp", "data_handler_string_l_o_8cpp.html", null ],
    [ "dataHandlerStringLO.h", "data_handler_string_l_o_8h.html", null ],
    [ "dataHandlerStringLT.cpp", "data_handler_string_l_t_8cpp.html", null ],
    [ "dataHandlerStringLT.h", "data_handler_string_l_t_8h.html", null ],
    [ "dataHandlerStringPN.cpp", "data_handler_string_p_n_8cpp.html", null ],
    [ "dataHandlerStringPN.h", "data_handler_string_p_n_8h.html", [
      [ "dataHandlerStringPN", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_p_n.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_p_n" ]
    ] ],
    [ "dataHandlerStringSH.cpp", "data_handler_string_s_h_8cpp.html", null ],
    [ "dataHandlerStringSH.h", "data_handler_string_s_h_8h.html", null ],
    [ "dataHandlerStringST.cpp", "data_handler_string_s_t_8cpp.html", null ],
    [ "dataHandlerStringST.h", "data_handler_string_s_t_8h.html", null ],
    [ "dataHandlerStringUI.cpp", "data_handler_string_u_i_8cpp.html", null ],
    [ "dataHandlerStringUI.h", "data_handler_string_u_i_8h.html", null ],
    [ "dataHandlerStringUnicode.cpp", "data_handler_string_unicode_8cpp.html", null ],
    [ "dataHandlerStringUnicode.h", "data_handler_string_unicode_8h.html", [
      [ "dataHandlerStringUnicode", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_unicode.html", null ]
    ] ],
    [ "dataHandlerStringUT.cpp", "data_handler_string_u_t_8cpp.html", null ],
    [ "dataHandlerStringUT.h", "data_handler_string_u_t_8h.html", null ],
    [ "dataHandlerTime.cpp", "data_handler_time_8cpp.html", null ],
    [ "dataHandlerTime.h", "data_handler_time_8h.html", [
      [ "dataHandlerTime", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_time.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_time" ]
    ] ],
    [ "dataSet.cpp", "data_set_8cpp.html", null ],
    [ "dataSet.h", "data_set_8h.html", null ],
    [ "dicomCodec.cpp", "dicom_codec_8cpp.html", null ],
    [ "dicomCodec.h", "dicom_codec_8h.html", "dicom_codec_8h" ],
    [ "dicomDict.cpp", "dicom_dict_8cpp.html", null ],
    [ "dicomDict.h", "dicom_dict_8h.html", null ],
    [ "dicomDir.cpp", "dicom_dir_8cpp.html", null ],
    [ "dicomDir.h", "dicom_dir_8h.html", null ],
    [ "drawBitmap.cpp", "draw_bitmap_8cpp.html", null ],
    [ "drawBitmap.h", "draw_bitmap_8h.html", "draw_bitmap_8h" ],
    [ "exception.cpp", "exception_8cpp.html", null ],
    [ "exception.h", "exception_8h.html", "exception_8h" ],
    [ "huffmanTable.cpp", "huffman_table_8cpp.html", null ],
    [ "huffmanTable.h", "huffman_table_8h.html", null ],
    [ "image.cpp", "image_8cpp.html", null ],
    [ "image.h", "image_8h.html", null ],
    [ "imebra.h", "imebra_8h.html", null ],
    [ "jpegCodec.cpp", "jpeg_codec_8cpp.html", null ],
    [ "jpegCodec.h", "jpeg_codec_8h.html", null ],
    [ "LUT.cpp", "_l_u_t_8cpp.html", null ],
    [ "LUT.h", "_l_u_t_8h.html", null ],
    [ "memory.cpp", "memory_8cpp.html", null ],
    [ "memory.h", "memory_8h.html", null ],
    [ "memoryStream.cpp", "memory_stream_8cpp.html", null ],
    [ "memoryStream.h", "memory_stream_8h.html", null ],
    [ "modalityVOILUT.cpp", "modality_v_o_i_l_u_t_8cpp.html", null ],
    [ "modalityVOILUT.h", "modality_v_o_i_l_u_t_8h.html", [
      [ "modalityVOILUTException", "classpuntoexe_1_1imebra_1_1transforms_1_1modality_v_o_i_l_u_t_exception.html", null ]
    ] ],
    [ "MONOCHROME1ToMONOCHROME2.cpp", "_m_o_n_o_c_h_r_o_m_e1_to_m_o_n_o_c_h_r_o_m_e2_8cpp.html", null ],
    [ "MONOCHROME1ToMONOCHROME2.h", "_m_o_n_o_c_h_r_o_m_e1_to_m_o_n_o_c_h_r_o_m_e2_8h.html", null ],
    [ "MONOCHROME1ToRGB.cpp", "_m_o_n_o_c_h_r_o_m_e1_to_r_g_b_8cpp.html", null ],
    [ "MONOCHROME1ToRGB.h", "_m_o_n_o_c_h_r_o_m_e1_to_r_g_b_8h.html", null ],
    [ "MONOCHROME2ToRGB.cpp", "_m_o_n_o_c_h_r_o_m_e2_to_r_g_b_8cpp.html", null ],
    [ "MONOCHROME2ToRGB.h", "_m_o_n_o_c_h_r_o_m_e2_to_r_g_b_8h.html", null ],
    [ "MONOCHROME2ToYBRFULL.cpp", "_m_o_n_o_c_h_r_o_m_e2_to_y_b_r_f_u_l_l_8cpp.html", null ],
    [ "MONOCHROME2ToYBRFULL.h", "_m_o_n_o_c_h_r_o_m_e2_to_y_b_r_f_u_l_l_8h.html", null ],
    [ "nullStream.h", "null_stream_8h.html", null ],
    [ "PALETTECOLORToRGB.cpp", "_p_a_l_e_t_t_e_c_o_l_o_r_to_r_g_b_8cpp.html", null ],
    [ "PALETTECOLORToRGB.h", "_p_a_l_e_t_t_e_c_o_l_o_r_to_r_g_b_8h.html", null ],
    [ "RGBToMONOCHROME2.cpp", "_r_g_b_to_m_o_n_o_c_h_r_o_m_e2_8cpp.html", null ],
    [ "RGBToMONOCHROME2.h", "_r_g_b_to_m_o_n_o_c_h_r_o_m_e2_8h.html", null ],
    [ "RGBToYBRFULL.cpp", "_r_g_b_to_y_b_r_f_u_l_l_8cpp.html", null ],
    [ "RGBToYBRFULL.h", "_r_g_b_to_y_b_r_f_u_l_l_8h.html", null ],
    [ "RGBToYBRPARTIAL.cpp", "_r_g_b_to_y_b_r_p_a_r_t_i_a_l_8cpp.html", null ],
    [ "RGBToYBRPARTIAL.h", "_r_g_b_to_y_b_r_p_a_r_t_i_a_l_8h.html", null ],
    [ "stream.cpp", "stream_8cpp.html", null ],
    [ "stream.h", "stream_8h.html", null ],
    [ "streamController.cpp", "stream_controller_8cpp.html", null ],
    [ "streamController.h", "stream_controller_8h.html", null ],
    [ "streamReader.cpp", "stream_reader_8cpp.html", null ],
    [ "streamReader.h", "stream_reader_8h.html", null ],
    [ "streamWriter.cpp", "stream_writer_8cpp.html", null ],
    [ "streamWriter.h", "stream_writer_8h.html", null ],
    [ "transaction.cpp", "transaction_8cpp.html", null ],
    [ "transaction.h", "transaction_8h.html", "transaction_8h" ],
    [ "transform.cpp", "transform_8cpp.html", null ],
    [ "transform.h", "transform_8h.html", null ],
    [ "transformHighBit.cpp", "transform_high_bit_8cpp.html", null ],
    [ "transformHighBit.h", "transform_high_bit_8h.html", null ],
    [ "transformsChain.cpp", "transforms_chain_8cpp.html", null ],
    [ "transformsChain.h", "transforms_chain_8h.html", null ],
    [ "viewHelper.cpp", "view_helper_8cpp.html", null ],
    [ "viewHelper.h", "view_helper_8h.html", null ],
    [ "VOILUT.cpp", "_v_o_i_l_u_t_8cpp.html", null ],
    [ "VOILUT.h", "_v_o_i_l_u_t_8h.html", null ],
    [ "waveform.cpp", "waveform_8cpp.html", null ],
    [ "waveform.h", "waveform_8h.html", null ],
    [ "YBRFULLToMONOCHROME2.cpp", "_y_b_r_f_u_l_l_to_m_o_n_o_c_h_r_o_m_e2_8cpp.html", null ],
    [ "YBRFULLToMONOCHROME2.h", "_y_b_r_f_u_l_l_to_m_o_n_o_c_h_r_o_m_e2_8h.html", null ],
    [ "YBRFULLToRGB.cpp", "_y_b_r_f_u_l_l_to_r_g_b_8cpp.html", null ],
    [ "YBRFULLToRGB.h", "_y_b_r_f_u_l_l_to_r_g_b_8h.html", null ],
    [ "YBRPARTIALToRGB.cpp", "_y_b_r_p_a_r_t_i_a_l_to_r_g_b_8cpp.html", null ],
    [ "YBRPARTIALToRGB.h", "_y_b_r_p_a_r_t_i_a_l_to_r_g_b_8h.html", null ]
];