var namespacepuntoexe =
[
    [ "imebra", null, [
      [ "charsetsList", null, [
        [ "charsetsListException", "classpuntoexe_1_1imebra_1_1charsets_list_1_1charsets_list_exception.html", null ],
        [ "charsetListExceptionDiffDefault", "classpuntoexe_1_1imebra_1_1charsets_list_1_1charset_list_exception_diff_default.html", null ]
      ] ],
      [ "codecs", null, [
        [ "codec", "classpuntoexe_1_1imebra_1_1codecs_1_1codec.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec" ],
        [ "codecException", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception" ],
        [ "codecExceptionWrongFormat", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_wrong_format.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_wrong_format" ],
        [ "codecExceptionCorruptedFile", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_corrupted_file.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_corrupted_file" ],
        [ "codecExceptionWrongTransferSyntax", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_wrong_transfer_syntax.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_wrong_transfer_syntax" ],
        [ "codecExceptionImageTooBig", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_image_too_big.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_exception_image_too_big" ],
        [ "codecFactory", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_factory.html", "classpuntoexe_1_1imebra_1_1codecs_1_1codec_factory" ],
        [ "dicomCodec", "classpuntoexe_1_1imebra_1_1codecs_1_1dicom_codec.html", "classpuntoexe_1_1imebra_1_1codecs_1_1dicom_codec" ],
        [ "dicomCodecException", "classpuntoexe_1_1imebra_1_1codecs_1_1dicom_codec_exception.html", "classpuntoexe_1_1imebra_1_1codecs_1_1dicom_codec_exception" ],
        [ "dicomCodecExceptionDepthLimitReached", "classpuntoexe_1_1imebra_1_1codecs_1_1dicom_codec_exception_depth_limit_reached.html", "classpuntoexe_1_1imebra_1_1codecs_1_1dicom_codec_exception_depth_limit_reached" ],
        [ "jpegCodec", "classpuntoexe_1_1imebra_1_1codecs_1_1jpeg_codec.html", "classpuntoexe_1_1imebra_1_1codecs_1_1jpeg_codec" ],
        [ "jpegCodecException", "classpuntoexe_1_1imebra_1_1codecs_1_1jpeg_codec_exception.html", null ],
        [ "jpegCodecCannotHandleSyntax", "classpuntoexe_1_1imebra_1_1codecs_1_1jpeg_codec_cannot_handle_syntax.html", "classpuntoexe_1_1imebra_1_1codecs_1_1jpeg_codec_cannot_handle_syntax" ]
      ] ],
      [ "handlers", null, [
        [ "dataHandler", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler" ],
        [ "dataHandlerDate", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date" ],
        [ "dataHandlerDateTimeBase", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date_time_base.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_date_time_base" ],
        [ "dataHandlerNumericBase", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_numeric_base.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_numeric_base" ],
        [ "dataHandlerNumeric", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_numeric.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_numeric" ],
        [ "dataHandlerRaw", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_raw.html", null ],
        [ "dataHandlerString", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string" ],
        [ "dataHandlerStringAE", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_e.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_e" ],
        [ "dataHandlerStringAS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_a_s" ],
        [ "dataHandlerStringCS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_c_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_c_s" ],
        [ "dataHandlerStringDS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_d_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_d_s" ],
        [ "dataHandlerStringIS", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_i_s.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_i_s" ],
        [ "dataHandlerStringPN", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_p_n.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_p_n" ],
        [ "dataHandlerStringUnicode", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_string_unicode.html", null ],
        [ "dataHandlerTime", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_time.html", "classpuntoexe_1_1imebra_1_1handlers_1_1data_handler_time" ]
      ] ],
      [ "transforms", null, [
        [ "colorTransforms", null, [
          [ "colorTransform", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1color_transform.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1color_transform" ],
          [ "colorTransformsFactory", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1color_transforms_factory.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1color_transforms_factory" ],
          [ "colorTransformsFactoryException", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1color_transforms_factory_exception.html", null ],
          [ "colorTransformsFactoryExceptionNoTransform", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1color_transforms_factory_exception_no_transform.html", null ],
          [ "MONOCHROME1ToMONOCHROME2", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e1_to_m_o_n_o_c_h_r_o_m_e2.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e1_to_m_o_n_o_c_h_r_o_m_e2" ],
          [ "MONOCHROME2ToMONOCHROME1", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e2_to_m_o_n_o_c_h_r_o_m_e1.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e2_to_m_o_n_o_c_h_r_o_m_e1" ],
          [ "MONOCHROME1ToRGB", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e1_to_r_g_b.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e1_to_r_g_b" ],
          [ "MONOCHROME2ToRGB", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e2_to_r_g_b.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e2_to_r_g_b" ],
          [ "MONOCHROME2ToYBRFULL", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e2_to_y_b_r_f_u_l_l.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_m_o_n_o_c_h_r_o_m_e2_to_y_b_r_f_u_l_l" ],
          [ "PALETTECOLORToRGB", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_p_a_l_e_t_t_e_c_o_l_o_r_to_r_g_b.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_p_a_l_e_t_t_e_c_o_l_o_r_to_r_g_b" ],
          [ "RGBToMONOCHROME2", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_r_g_b_to_m_o_n_o_c_h_r_o_m_e2.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_r_g_b_to_m_o_n_o_c_h_r_o_m_e2" ],
          [ "RGBToYBRFULL", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_r_g_b_to_y_b_r_f_u_l_l.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_r_g_b_to_y_b_r_f_u_l_l" ],
          [ "RGBToYBRPARTIAL", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_r_g_b_to_y_b_r_p_a_r_t_i_a_l.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_r_g_b_to_y_b_r_p_a_r_t_i_a_l" ],
          [ "YBRFULLToMONOCHROME2", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_y_b_r_f_u_l_l_to_m_o_n_o_c_h_r_o_m_e2.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_y_b_r_f_u_l_l_to_m_o_n_o_c_h_r_o_m_e2" ],
          [ "YBRFULLToRGB", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_y_b_r_f_u_l_l_to_r_g_b.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_y_b_r_f_u_l_l_to_r_g_b" ],
          [ "YBRPARTIALToRGB", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_y_b_r_p_a_r_t_i_a_l_to_r_g_b.html", "classpuntoexe_1_1imebra_1_1transforms_1_1color_transforms_1_1_y_b_r_p_a_r_t_i_a_l_to_r_g_b" ]
        ] ],
        [ "applyLUTException", "classpuntoexe_1_1imebra_1_1transforms_1_1apply_l_u_t_exception.html", null ],
        [ "applyLUT", "classpuntoexe_1_1imebra_1_1transforms_1_1apply_l_u_t.html", "classpuntoexe_1_1imebra_1_1transforms_1_1apply_l_u_t" ],
        [ "modalityVOILUTException", "classpuntoexe_1_1imebra_1_1transforms_1_1modality_v_o_i_l_u_t_exception.html", null ],
        [ "modalityVOILUT", "classpuntoexe_1_1imebra_1_1transforms_1_1modality_v_o_i_l_u_t.html", "classpuntoexe_1_1imebra_1_1transforms_1_1modality_v_o_i_l_u_t" ],
        [ "transform", "classpuntoexe_1_1imebra_1_1transforms_1_1transform.html", "classpuntoexe_1_1imebra_1_1transforms_1_1transform" ],
        [ "transformHandlers", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_handlers.html", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_handlers" ],
        [ "transformException", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_exception.html", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_exception" ],
        [ "transformExceptionInvalidArea", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_exception_invalid_area.html", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_exception_invalid_area" ],
        [ "transformHighBit", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_high_bit.html", "classpuntoexe_1_1imebra_1_1transforms_1_1transform_high_bit" ],
        [ "transformsChain", "classpuntoexe_1_1imebra_1_1transforms_1_1transforms_chain.html", "classpuntoexe_1_1imebra_1_1transforms_1_1transforms_chain" ],
        [ "VOILUT", "classpuntoexe_1_1imebra_1_1transforms_1_1_v_o_i_l_u_t.html", "classpuntoexe_1_1imebra_1_1transforms_1_1_v_o_i_l_u_t" ]
      ] ],
      [ "buffer", "classpuntoexe_1_1imebra_1_1buffer.html", "classpuntoexe_1_1imebra_1_1buffer" ],
      [ "bufferException", "classpuntoexe_1_1imebra_1_1buffer_exception.html", "classpuntoexe_1_1imebra_1_1buffer_exception" ],
      [ "bufferExceptionUnknownType", "classpuntoexe_1_1imebra_1_1buffer_exception_unknown_type.html", "classpuntoexe_1_1imebra_1_1buffer_exception_unknown_type" ],
      [ "data", "classpuntoexe_1_1imebra_1_1data.html", "classpuntoexe_1_1imebra_1_1data" ],
      [ "dataCollectionIterator", "classpuntoexe_1_1imebra_1_1data_collection_iterator.html", "classpuntoexe_1_1imebra_1_1data_collection_iterator" ],
      [ "dataCollection", "classpuntoexe_1_1imebra_1_1data_collection.html", "classpuntoexe_1_1imebra_1_1data_collection" ],
      [ "dataGroup", "classpuntoexe_1_1imebra_1_1data_group.html", "classpuntoexe_1_1imebra_1_1data_group" ],
      [ "dataSet", "classpuntoexe_1_1imebra_1_1data_set.html", "classpuntoexe_1_1imebra_1_1data_set" ],
      [ "dataSetException", "classpuntoexe_1_1imebra_1_1data_set_exception.html", null ],
      [ "dataSetExceptionDifferentFormat", "classpuntoexe_1_1imebra_1_1data_set_exception_different_format.html", null ],
      [ "dataSetExceptionUnknownTransferSyntax", "classpuntoexe_1_1imebra_1_1data_set_exception_unknown_transfer_syntax.html", null ],
      [ "dataSetExceptionWrongFrame", "classpuntoexe_1_1imebra_1_1data_set_exception_wrong_frame.html", null ],
      [ "dataSetExceptionOldFormat", "classpuntoexe_1_1imebra_1_1data_set_exception_old_format.html", null ],
      [ "dataSetImageDoesntExist", "classpuntoexe_1_1imebra_1_1data_set_image_doesnt_exist.html", "classpuntoexe_1_1imebra_1_1data_set_image_doesnt_exist" ],
      [ "dataSetCorruptedOffsetTable", "classpuntoexe_1_1imebra_1_1data_set_corrupted_offset_table.html", "classpuntoexe_1_1imebra_1_1data_set_corrupted_offset_table" ],
      [ "dicomDictionary", "classpuntoexe_1_1imebra_1_1dicom_dictionary.html", "classpuntoexe_1_1imebra_1_1dicom_dictionary" ],
      [ "directoryRecord", "classpuntoexe_1_1imebra_1_1directory_record.html", "classpuntoexe_1_1imebra_1_1directory_record" ],
      [ "dicomDir", "classpuntoexe_1_1imebra_1_1dicom_dir.html", "classpuntoexe_1_1imebra_1_1dicom_dir" ],
      [ "dicomDirException", "classpuntoexe_1_1imebra_1_1dicom_dir_exception.html", "classpuntoexe_1_1imebra_1_1dicom_dir_exception" ],
      [ "dicomDirCircularReferenceException", "classpuntoexe_1_1imebra_1_1dicom_dir_circular_reference_exception.html", "classpuntoexe_1_1imebra_1_1dicom_dir_circular_reference_exception" ],
      [ "dicomDirUnknownDirectoryRecordType", "classpuntoexe_1_1imebra_1_1dicom_dir_unknown_directory_record_type.html", "classpuntoexe_1_1imebra_1_1dicom_dir_unknown_directory_record_type" ],
      [ "drawBitmapException", "classpuntoexe_1_1imebra_1_1draw_bitmap_exception.html", null ],
      [ "drawBitmapExceptionInvalidArea", "classpuntoexe_1_1imebra_1_1draw_bitmap_exception_invalid_area.html", null ],
      [ "drawBitmap", "classpuntoexe_1_1imebra_1_1draw_bitmap.html", "classpuntoexe_1_1imebra_1_1draw_bitmap" ],
      [ "image", "classpuntoexe_1_1imebra_1_1image.html", "classpuntoexe_1_1imebra_1_1image" ],
      [ "imageException", "classpuntoexe_1_1imebra_1_1image_exception.html", "classpuntoexe_1_1imebra_1_1image_exception" ],
      [ "imageExceptionUnknownDepth", "classpuntoexe_1_1imebra_1_1image_exception_unknown_depth.html", null ],
      [ "imageExceptionUnknownColorSpace", "classpuntoexe_1_1imebra_1_1image_exception_unknown_color_space.html", null ],
      [ "imageExceptionInvalidSize", "classpuntoexe_1_1imebra_1_1image_exception_invalid_size.html", null ],
      [ "lut", "classpuntoexe_1_1imebra_1_1lut.html", "classpuntoexe_1_1imebra_1_1lut" ],
      [ "palette", "classpuntoexe_1_1imebra_1_1palette.html", "classpuntoexe_1_1imebra_1_1palette" ],
      [ "lutException", "classpuntoexe_1_1imebra_1_1lut_exception.html", null ],
      [ "lutExceptionWrongIndex", "classpuntoexe_1_1imebra_1_1lut_exception_wrong_index.html", null ],
      [ "lutExceptionCorrupted", "classpuntoexe_1_1imebra_1_1lut_exception_corrupted.html", null ],
      [ "transaction", "classpuntoexe_1_1imebra_1_1transaction.html", "classpuntoexe_1_1imebra_1_1transaction" ],
      [ "view", "classpuntoexe_1_1imebra_1_1view.html", "classpuntoexe_1_1imebra_1_1view" ],
      [ "waveform", "classpuntoexe_1_1imebra_1_1waveform.html", "classpuntoexe_1_1imebra_1_1waveform" ]
    ] ],
    [ "ptr", "classpuntoexe_1_1ptr.html", "classpuntoexe_1_1ptr" ],
    [ "baseObject", "classpuntoexe_1_1base_object.html", "classpuntoexe_1_1base_object" ],
    [ "lockObject", "classpuntoexe_1_1lock_object.html", "classpuntoexe_1_1lock_object" ],
    [ "lockMultipleObjects", "classpuntoexe_1_1lock_multiple_objects.html", "classpuntoexe_1_1lock_multiple_objects" ],
    [ "baseStream", "classpuntoexe_1_1base_stream.html", "classpuntoexe_1_1base_stream" ],
    [ "streamException", "classpuntoexe_1_1stream_exception.html", null ],
    [ "streamExceptionOpen", "classpuntoexe_1_1stream_exception_open.html", null ],
    [ "streamExceptionRead", "classpuntoexe_1_1stream_exception_read.html", null ],
    [ "streamExceptionWrite", "classpuntoexe_1_1stream_exception_write.html", null ],
    [ "streamExceptionClose", "classpuntoexe_1_1stream_exception_close.html", null ],
    [ "charsetConversionException", "classpuntoexe_1_1charset_conversion_exception.html", null ],
    [ "charsetConversionExceptionNoTable", "classpuntoexe_1_1charset_conversion_exception_no_table.html", null ],
    [ "charsetConversionExceptionNoSupportedTable", "classpuntoexe_1_1charset_conversion_exception_no_supported_table.html", null ],
    [ "charsetConversionExceptionUtfSizeNotSupported", "classpuntoexe_1_1charset_conversion_exception_utf_size_not_supported.html", null ],
    [ "criticalSection", "classpuntoexe_1_1critical_section.html", "classpuntoexe_1_1critical_section" ],
    [ "lockCriticalSection", "classpuntoexe_1_1lock_critical_section.html", "classpuntoexe_1_1lock_critical_section" ],
    [ "exceptionInfo", "classpuntoexe_1_1exception_info.html", "classpuntoexe_1_1exception_info" ],
    [ "exceptionsManager", "classpuntoexe_1_1exceptions_manager.html", "classpuntoexe_1_1exceptions_manager" ],
    [ "huffmanTable", "classpuntoexe_1_1huffman_table.html", "classpuntoexe_1_1huffman_table" ],
    [ "memory", "classpuntoexe_1_1memory.html", "classpuntoexe_1_1memory" ],
    [ "memoryPool", "classpuntoexe_1_1memory_pool.html", "classpuntoexe_1_1memory_pool" ],
    [ "memoryStream", "classpuntoexe_1_1memory_stream.html", "classpuntoexe_1_1memory_stream" ],
    [ "nullStream", "classpuntoexe_1_1null_stream.html", "classpuntoexe_1_1null_stream" ],
    [ "stream", "classpuntoexe_1_1stream.html", "classpuntoexe_1_1stream" ],
    [ "streamController", "classpuntoexe_1_1stream_controller.html", "classpuntoexe_1_1stream_controller" ],
    [ "streamExceptionEOF", "classpuntoexe_1_1stream_exception_e_o_f.html", null ],
    [ "streamJpegTagInStream", "classpuntoexe_1_1stream_jpeg_tag_in_stream.html", null ],
    [ "streamReader", "classpuntoexe_1_1stream_reader.html", "classpuntoexe_1_1stream_reader" ],
    [ "streamWriter", "classpuntoexe_1_1stream_writer.html", "classpuntoexe_1_1stream_writer" ]
];